spring:
  servlet:
    multipart:
      # ??? ??? ?? ??
      location: C:\lecture\10_spring-web-mvc\chap06-file-upload-lecture-source
      # ??? ??? ?? ?? ??
      max-file-size: 10MB
      #?? ? ??? ??? ?? ?? ??
      max-request-size: 10MB
  mvc:
    static-path-pattern: /static/**